export {default as Home} from './Home'
export {default as About} from './About'
export {default as PreviousWork} from './PreviousWork'
export {default as Project} from './Project'
export {default as Contact} from './Contact'
export {default as NavBar} from './NavBar'
export {default as Footer} from './Footer'